import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";

import { cn } from "@/lib/utils";
import QueryProvider from "@/lib/reactQuery/QueryProvider";
import SideMenu from "@/components/SideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
        {/* <QueryProvider> */}
        {children}
        {/* </QueryProvider> */}
      </body>
    </html>
  );
}
